In [1]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn import datasets
import numpy as np
import pandas as pd

In [2]:
crx = pd.read_csv('file:///C:/Users/renna/Downloads/crx.data')

In [3]:
crx

     b  30.83       0  u  g   w   v  1.25  t t.1  01  f g.1  00202  0.1  +
0    a  58.67   4.460  u  g   q   h  3.04  t   t   6  f   g  00043  560  +
1    a  24.50   0.500  u  g   q   h  1.50  t   f   0  f   g  00280  824  +
2    b  27.83   1.540  u  g   w   v  3.75  t   t   5  t   g  00100    3  +
3    b  20.17   5.625  u  g   w   v  1.71  t   f   0  f   s  00120    0  +
4    b  32.08   4.000  u  g   m   v  2.50  t   f   0  t   g  00360    0  +
..  ..    ...     ... .. ..  ..  ..   ... ..  ..  .. ..  ..    ...  ... ..
684  b  21.08  10.085  y  p   e   h  1.25  f   f   0  f   g  00260    0  -
685  a  22.67   0.750  u  g   c   v  2.00  f   t   2  t   g  00200  394  -
686  a  25.25  13.500  y  p  ff  ff  2.00  f   t   1  t   g  00200    1  -
687  b  17.92   0.205  u  g  aa   v  0.04  f   f   0  f   g  00280  750  -
688  b  35.00   3.375  u  g   c   h  8.29  f   f   0  t   g  00000    0  -

[689 rows x 16 columns]

In [4]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in list(crx.columns):
    if crx[i].dtype=='object':
        crx[i]=le.fit_transform(crx[i])

In [5]:
y=crx['30.83']
x=crx.drop('30.83',axis=1)

In [6]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0,test_size=0.2)

In [7]:
knn = KNeighborsClassifier(n_neighbors=6)

In [8]:
knn.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=6, p=2,
                     weights='uniform')

In [9]:
y_pred = knn.predict(x_train)

In [10]:
y_pred

array([ 23, 185,  64,  13,  66,   6,   2,  59,  44,  31,  22,  19,  20,
        13,  48, 173,  64,  71,   3,  41,  11,  26,   5, 142,  71,  76,
        45,   4,  22,  27,  45,  12,  60,  44,  36, 129, 125,  55,  11,
        94,  49,  12, 142,  74, 100, 131,  82,  48,  18,  76,   5, 164,
        81,  37,   2, 101,  74,  98,  38,  66,  24,  46,   6,  58,  52,
        83,  10,  23,  41,  69,  52,  94,  75,  20,  89,  41,  11,  45,
       133,  75,  69,  46,  49,  90,   8,  21,  53,  31,   2,  37, 178,
        40,  82, 119,   3,  38, 119,  50,  94,  17,   3,   4,  69,  72,
        52,  32, 171, 348,  53, 144, 108, 120,  43, 108,   0,  27, 131,
        28,  62, 100,  26,  63,  76,  46,  26,  64, 133,  39, 144,  50,
        17,  10,  31,  53,  31,  10,   6,   7,  48,  58,  14,   5,   6,
        71, 250,  11,   6,   4,  96,  19,  66,   0,  26,  31,  18,  61,
        58,   3,  22, 129,  76,  31,  39,  32,  82,  13,  24,  89,  49,
        12,  98, 219,  71,  19,  31, 125,  27,  83,  61,   6,  32,   7,
       173,  27, 250, 113,  18, 119,  20,  44,  74,  75,   6,  46,  13,
         0,  12,  11,  64,  97,  51,  23,  51,  58,  31,  24,  13,  10,
        94,  55,   0,  59,  31,  97,   9,  44,  75,  11, 135,  74,   9,
         5,  76,  94,  10,   5,   9,  41,   6,  57,  12,  31,  10,   9,
        61, 119, 120,  12,  50, 178,  26,   9,   0,   4,  90,  12,  17,
        18,  23,  17,  24,  97,  18, 292,  46,  22,  29,  27, 131,  36,
        59, 185, 134,  28,   5,  46,  53,  12,  31, 171,  38,   6,  37,
         6,  55,  49,  65,  12,  28,  46,  28,   8, 108,  26,   3,  46,
       119, 108,  38,  45, 135,   7,   9,  44, 125, 197,  26,  31,  50,
        45, 135,   5,  94, 119,   9,  36,  76,  26,  31,  20,  28,  90,
       125,  10,  17,  32,  48,  75,  39,  71,  51,  11,  10, 173,  19,
        15,  46, 185,   4, 348,  31,  48,  10,   7,  46,  90,  17,  99,
       101, 129,  23,  27,  52,  38,  23,  49,  12,  55,  28,  75,  34,
        26,   2,  21,  17,  51, 144,  69,  26,  31,  12,  64,  55,   7,
        31, 135,  22, 119,   8,  32,   4, 133,   5,   2,  58, 135, 122,
        17,  39,  55,  62,  11,  98,  12, 100, 164,  23,  48,  19,   3,
        89,  55, 188,  66,  52,  55,  64,  31,  28,  98,  74,  31,   9,
        23,  46,  23,  82,  28,  10,  74, 108,  59,   6, 133,  76,  62,
        61,  31,  42,   4,  46,  17,  51,  43,  64,  90,  38,  46,  48,
        80,  10,  31,  19,  50,  98,  45,  84,  96, 140,  32, 135,  19,
        69,  37,  12,  72,  14,   9,  23,  39, 119,  41,  17,  90,  73,
        24,  55,  32,  76,  43,  12,  75,  75,  74,  44,  64,  75,  41,
        49,  97,  38,  10, 144,  75,  31,   8,  61, 144,  46,  98,  34,
        22,  20,  22, 178,  82, 140,  64,  22,  63,  63,  24, 173,  78,
        49,  27,  87,  63, 140,   0,  50,  13, 130,  62,  74, 135, 120,
       108,  64, 173,   3, 131,  55,  19,  28,   0,  54, 100,   2,  17,
        49,   3,  31,  28,  19,  17,  26,  26,  17,  61, 137, 129,  31,
         7,  72,  31,   3,  89,  75,  10,  78,  34,  46,  75,  38,  10,
        36,  39,  20,  87,  31])